version: '1'
services:
  nodejs-express:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=goher
      - MONGO_INITDB_ROOT_PASSWORD=Cigoher22
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:

